# Generated by Django 3.2.4 on 2021-06-09 08:07

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='images/idea/header/')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(related_name='category_idea', to='news.Category')),
                ('like_idea', models.ManyToManyField(blank=True, related_name='the_like', to=settings.AUTH_USER_MODEL)),
                ('unlike_idea', models.ManyToManyField(blank=True, related_name='the_like_unlike', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datetime'],
                'permissions': [('all', 'all of the permissions')],
            },
        ),
        migrations.CreateModel(
            name='CommentIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_idea', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_idea', to='idea.idea')),
                ('like_comment_idea', models.ManyToManyField(blank=True, related_name='comment_idea_like', to=settings.AUTH_USER_MODEL)),
                ('unlike_comment_idea', models.ManyToManyField(blank=True, related_name='comment_idea_unlike', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
