# Generated by Django 3.2.3 on 2021-05-24 08:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
