# Generated by Django 3.2.3 on 2021-05-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_comment_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Google_News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=355)),
                ('site', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/news/google_news/')),
            ],
            options={
                'ordering': ['-date_time'],
                'permissions': [('all', 'all of the permissions')],
            },
        ),
    ]
