# Generated by Django 3.2 on 2021-05-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/news/header/'),
        ),
    ]
