# Generated by Django 3.2.3 on 2021-05-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_google_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='google_news',
            name='category',
            field=models.ManyToManyField(related_name='category_google_news', to='news.Category'),
        ),
    ]
