# Generated by Django 3.2.3 on 2021-05-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_google_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='google_news',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
