# Generated by Django 3.2.3 on 2021-05-29 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_google_news_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-datetime'], 'permissions': [('all', 'all of the permissions')]},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='date',
            new_name='datetime',
        ),
        migrations.DeleteModel(
            name='Google_News',
        ),
    ]
