# Generated by Django 3.2.3 on 2021-06-08 13:53

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20210529_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to=news.models.get_header_image_filepath),
        ),
    ]
