# Generated by Django 3.2.3 on 2021-05-24 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210523_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('all', 'all of the permissions')]},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='hide_email',
        ),
    ]
