# Generated by Django 3.2.3 on 2021-05-19 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
